# Generated by Django 5.2.1 on 2025-06-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo',
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_interno',
            field=models.CharField(default='TEMP', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
