# Generated by Django 5.2.2 on 2025-06-14 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_movimiento_almacen_movimiento_hora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='hora',
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='almacen',
            field=models.CharField(default='principal', max_length=100),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
