# Generated by Django 5.2.2 on 2025-06-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_movimiento_hora_alter_movimiento_almacen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='almacen',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
