# Generated by Django 5.2.2 on 2025-06-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_movimiento_almacen_alter_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='almacen',
            field=models.CharField(default='principal', max_length=100),
        ),
    ]
